name: store-on-wheels-dev
concurrency:
    group: store-on-wheels-dev
    cancel-in-progress: true

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout current branch
              uses: actions/checkout@v4
            - name: Setup .NET 8x
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.x'
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: '20.x'
            - name: Install .NET Dependencies
              run: dotnet restore
            - name: Install npm modules
              run: |
                  cd src/storeonwheels.client
                  npm ci
            - name: Build JS
              run: |
                  cd src/storeonwheels.client
                  npm run build
            - name: Build .NET
              run: dotnet build
